### ISSUE TITLE
(Question) Most ddi files of V2 cannot be extracted

### ISSUE THREAD

**Issue by Cinelie** [ain-soph/ddb-extraction#2]
As the title said,most v2 libraries' ddi files will cause the AssertionError
and only VY2V5 can be fully renamed,VY2V2 and V3's ddi.yam have the unknow wav names which do not be inclued in the extract samples.(Seem that the second pitch's wav name have an error)Miku V2 Dark can not be fully extract（it can only extract 1299 files in totally 1473 files）

**Comment by ain-soph** [comment]
It might be helpful for others if we communicate using English here.

I'm using LuoTianyi V4 Meng as my main reference for the implementation.

If there is any AssertionError, that means my current ddi file structure prediction is not perfect (https://1drv.ms/u/s!AgxVwvz3Kj1Ek49YzGjngt49krIZvQ). I never expect it to be perfect though.

I can't spend too much time on this, and it doesn't seem to be hopeful to get everything working. But any discussion and PR is welcome.

**Comment by ain-soph** [comment]
I see most errors come from the old V2 and V3 libraries. I think it'll be fine to simply use the new version instead. Working on old standards is quite painful.

**Comment by Cinelie** [comment]
> 

Oh,I see.
I guess that problem may be caused by different PHDC part of ddi.
Some libraries do not have newer version or their newer version use the different sound samples,so I want to remake them to a higher quality.(I do not think most people will not be interested in a more fluent Miku V2)
May a phoneme list extractor be possible?Just show which cv,vv and vc samples the ddi have.

**Comment by ain-soph** [comment]
It might not be easy to encode everything back to ddi and ddb format.

Currently I'm only doing the decode job. You can see there are a bunch of unknown bytes in the file, and especially some hash-like bytes. We can't calculate them, and the file validation will fail if we encode our diy stuffs.  
But it might work if they don't have any validation mechanism.

Thanks for posting this issue again!

**Comment by Cinelie** [comment]
> It might not be easy to encode everything back to ddi and ddb format.
> 
> Currently I'm only doing the decode job. You can see there are a bunch of unknown bytes in the file, and especially some hash-like bytes. We can't calculate them, and the file validation will fail if we encode our diy stuffs. But it might work if they don't have any validation mechanism.
> 
> Thanks for posting this issue again!

Well,actually I do not have a plan to encode them to vocaloid.Vocaloid's oto making will be overly concerned with details.An UTAU vb with world vocoder will be easier and more useful.
